fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
public:
    resource: "@PublicBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: '@AppBundle/Controller/'
    type: annotation
